### ISSUE TITLE
Why have package version?

### ISSUE THREAD

**Issue by martindsouza** [insum-labs/plsql-and-sql-coding-guidelines#3]
From https://github.com/insum-labs/plsql-and-sql-coding-guidelines/blob/master/docs/3-coding-style/coding-style.md what is the purpose of a package version number?

Related to #2

**Comment by rimblas** [comment]
@martindsouza  I thought #2 was about the package version.  Could we keep it as one discussion?

**Comment by RichardSoule** [comment]
Closed as duplicate.

**Comment by martindsouza** [comment]
This is not a dup. #2 was about listing all the changes in a package. This is why even have a function to store the package version.

**Comment by RichardSoule** [comment]
Reasons were provided in the other issue.

Reason:

REST Services configured on DEV/TEST/PROD (etc.) allow a simple report of what version of each package is currently _actually_ in each database.

This works both for organizations that are using version control and for organizations that are not using version control.

**Comment by martindsouza** [comment]
@RichardSoule why do REST services need to know the version of each package?

**Comment by RichardSoule** [comment]
@martindsouza 

Let's say you have four databases:

DEV
TEST
QA
PROD

Each environment can be at a slightly different version based on where it is in the development cycle.

A common thing for us to do is to create REST services in each environment that allow us to query each package's version and then combine them together into an APEX report that says:

Package Name  DEV  TEST  QA  PROD
employee_api    2.0    1.7     1.6  1.5
next package     1.0     1.0    1.0   1.0
next package     1.2      1.1   1.0   1.0

That said, of course, you could the same with database links instead of REST services...

**Comment by RichardSoule** [comment]
Version functions for packages are very useful. Updated article with comments about version control and optionality.
